version: '3'

services:
  tvsports.api:
    image: tvsports.api:dev
    build:
      args:
        source: obj/Docker/empty/
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_tvsports.api$
    volumes:
      - C:\Users\pierr\source\repos\TvSports\Src\TvSports\TvSports.Api:/app
      - C:\Users\pierr\vsdbg:/remote_debugger:ro
      #- $nuget_user_folder_tvsports.api$:/root/.nuget/packages:ro
#$nuget_fallback_packages_volume_mapping_tvsports.api$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_tvsports.api$ bin/Debug/netcoreapp2.0/TvSports.Api.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
