// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;
using TvSports.Infrastructure.Data;

namespace TvSports.Infrastructure.Migrations
{
    [DbContext(typeof(TvSportsContext))]
    [Migration("20171110172442_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("Relational:Sequence:.Channel_hilo", "'Channel_hilo', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.Competition_hilo", "'Competition_hilo', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.Match_hilo", "'Match_hilo', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.Participant_hilo", "'Participant_hilo', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.Sport_hilo", "'Sport_hilo', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.Zone_hilo", "'Zone_hilo', '', '1', '10', '', '', 'Int64', 'False'");

            modelBuilder.Entity("TvSports.Core.Entities.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Npgsql:HiLoSequenceName", "Channel_hilo")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Channel");
                });

            modelBuilder.Entity("TvSports.Core.Entities.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Npgsql:HiLoSequenceName", "Competition_hilo")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("SportFK")
                        .IsRequired();

                    b.Property<int?>("ZoneFK")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("SportFK");

                    b.HasIndex("ZoneFK");

                    b.ToTable("Competition");
                });

            modelBuilder.Entity("TvSports.Core.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Npgsql:HiLoSequenceName", "Match_hilo")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SequenceHiLo);

                    b.Property<DateTime>("EndDate");

                    b.Property<int>("ParticipantAwayId");

                    b.Property<int>("ParticipantHomeId");

                    b.Property<int?>("PointsAxay");

                    b.Property<int?>("PointsHome");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantAwayId");

                    b.HasIndex("ParticipantHomeId");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("TvSports.Core.Entities.ParticipantBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Npgsql:HiLoSequenceName", "Participant_hilo")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Participant");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ParticipantBase");
                });

            modelBuilder.Entity("TvSports.Core.Entities.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Npgsql:HiLoSequenceName", "Sport_hilo")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sport");
                });

            modelBuilder.Entity("TvSports.Core.Entities.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Npgsql:HiLoSequenceName", "Zone_hilo")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<int?>("ParentId");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("Zone");
                });

            modelBuilder.Entity("TvSports.Core.Entities.Player", b =>
                {
                    b.HasBaseType("TvSports.Core.Entities.ParticipantBase");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.ToTable("Player");

                    b.HasDiscriminator().HasValue("Player");
                });

            modelBuilder.Entity("TvSports.Core.Entities.Team", b =>
                {
                    b.HasBaseType("TvSports.Core.Entities.ParticipantBase");


                    b.ToTable("Team");

                    b.HasDiscriminator().HasValue("Team");
                });

            modelBuilder.Entity("TvSports.Core.Entities.Competition", b =>
                {
                    b.HasOne("TvSports.Core.Entities.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportFK")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TvSports.Core.Entities.Zone", "Zone")
                        .WithMany("Competitions")
                        .HasForeignKey("ZoneFK")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TvSports.Core.Entities.Match", b =>
                {
                    b.HasOne("TvSports.Core.Entities.ParticipantBase", "ParticipantAway")
                        .WithMany()
                        .HasForeignKey("ParticipantAwayId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TvSports.Core.Entities.ParticipantBase", "ParticipantHome")
                        .WithMany()
                        .HasForeignKey("ParticipantHomeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TvSports.Core.Entities.Zone", b =>
                {
                    b.HasOne("TvSports.Core.Entities.Zone", "Parent")
                        .WithMany("ChildrenZone")
                        .HasForeignKey("ParentId");
                });
#pragma warning restore 612, 618
        }
    }
}
